--- 
title: "NBA Shooting Pattern Analysis"
author: "Anne Lin, Yanbing Chen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Basketball is a team sport in which the goal is to try to outscore the amount in a fixed amount of time. Points are scored (either 2 or 3 points) by putting the ball throw a hoop on one end of the court. An attempt at putting the ball throw the hoop is known as a "shot". If helpful, here are rules of basketball: https://en.wikipedia.org/wiki/Rules_of_basketball.

The National Basketball Association (NBA) is the professional basketball league in the United States and provides a nice website with many statistics gathered on teams and players in the league: https://www.nba.com/stats/.

As one of the most popular athletic leagues, NBA attracts elite players and these players represent the highest level of basketball in the world. However, the shooting behavior varies from player to player and even team to team. Therefore, intrigued by a passion for basketball and the abundance of data resources on the NBA website, we decided to implore the pattern of shooting behaviors in NBA for our final project and hope to take a small glance on what we are curious about through exploratory data analysis and visualization.

We propose the following questions to answer:

1. (On League Level)
We will give a overall glance at the dataset of last season to have a basic understanding on the shooting behaviors.

2. (On Team Level)
Basketball is a team-played game and each team has its own style and culture. From the perspective of team, we are going to look for some differences between shooting behaviors preferences and learn the relationship between the shooting patterns and period, field goal percentage, etc.

3. (On Player Level)
We choose three most popular players, Stephen Curry, Lebron James and Giannis Antetokounmpo to investigate their shooting choices and look at how other variables could influence their shooting decision such as in differnet periods of game.
